// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: tsynctl/tsynctl.proto

package tsynctl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsynctl_tsynctl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tsynctl_tsynctl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tsynctl_tsynctl_proto_rawDescGZIP(), []int{0}
}

// The reply message containing status of Get IPC Server status
type StatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsynctl_tsynctl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_tsynctl_tsynctl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_tsynctl_tsynctl_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// The response message containing the mode
type ModeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ModeReply) Reset() {
	*x = ModeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsynctl_tsynctl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeReply) ProtoMessage() {}

func (x *ModeReply) ProtoReflect() protoreflect.Message {
	mi := &file_tsynctl_tsynctl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeReply.ProtoReflect.Descriptor instead.
func (*ModeReply) Descriptor() ([]byte, []int) {
	return file_tsynctl_tsynctl_proto_rawDescGZIP(), []int{2}
}

func (x *ModeReply) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// The response message containing the mode
type TimeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TimeReply) Reset() {
	*x = TimeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsynctl_tsynctl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeReply) ProtoMessage() {}

func (x *TimeReply) ProtoReflect() protoreflect.Message {
	mi := &file_tsynctl_tsynctl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeReply.ProtoReflect.Descriptor instead.
func (*TimeReply) Descriptor() ([]byte, []int) {
	return file_tsynctl_tsynctl_proto_rawDescGZIP(), []int{3}
}

func (x *TimeReply) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ClassReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Class int32 `protobuf:"varint,1,opt,name=class,proto3" json:"class,omitempty"`
}

func (x *ClassReply) Reset() {
	*x = ClassReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsynctl_tsynctl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassReply) ProtoMessage() {}

func (x *ClassReply) ProtoReflect() protoreflect.Message {
	mi := &file_tsynctl_tsynctl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassReply.ProtoReflect.Descriptor instead.
func (*ClassReply) Descriptor() ([]byte, []int) {
	return file_tsynctl_tsynctl_proto_rawDescGZIP(), []int{4}
}

func (x *ClassReply) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

type AlarmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Val  int32 `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	Prev int32 `protobuf:"varint,3,opt,name=prev,proto3" json:"prev,omitempty"`
}

func (x *AlarmReply) Reset() {
	*x = AlarmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsynctl_tsynctl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmReply) ProtoMessage() {}

func (x *AlarmReply) ProtoReflect() protoreflect.Message {
	mi := &file_tsynctl_tsynctl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmReply.ProtoReflect.Descriptor instead.
func (*AlarmReply) Descriptor() ([]byte, []int) {
	return file_tsynctl_tsynctl_proto_rawDescGZIP(), []int{5}
}

func (x *AlarmReply) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AlarmReply) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *AlarmReply) GetPrev() int32 {
	if x != nil {
		return x.Prev
	}
	return 0
}

type ParamsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile   int32 `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Domain    int32 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Forward   int32 `protobuf:"varint,3,opt,name=forward,proto3" json:"forward,omitempty"`
	TwoStep   int32 `protobuf:"varint,4,opt,name=twoStep,proto3" json:"twoStep,omitempty"`
	Priority2 int32 `protobuf:"varint,5,opt,name=priority2,proto3" json:"priority2,omitempty"`
	PpsOut    int32 `protobuf:"varint,6,opt,name=ppsOut,proto3" json:"ppsOut,omitempty"`
	Mhz10Out  int32 `protobuf:"varint,7,opt,name=mhz10Out,proto3" json:"mhz10Out,omitempty"`
	SyncePort int32 `protobuf:"varint,8,opt,name=syncePort,proto3" json:"syncePort,omitempty"`
	SyncOpt   int32 `protobuf:"varint,9,opt,name=syncOpt,proto3" json:"syncOpt,omitempty"`
}

func (x *ParamsReply) Reset() {
	*x = ParamsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsynctl_tsynctl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsReply) ProtoMessage() {}

func (x *ParamsReply) ProtoReflect() protoreflect.Message {
	mi := &file_tsynctl_tsynctl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsReply.ProtoReflect.Descriptor instead.
func (*ParamsReply) Descriptor() ([]byte, []int) {
	return file_tsynctl_tsynctl_proto_rawDescGZIP(), []int{6}
}

func (x *ParamsReply) GetProfile() int32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *ParamsReply) GetDomain() int32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

func (x *ParamsReply) GetForward() int32 {
	if x != nil {
		return x.Forward
	}
	return 0
}

func (x *ParamsReply) GetTwoStep() int32 {
	if x != nil {
		return x.TwoStep
	}
	return 0
}

func (x *ParamsReply) GetPriority2() int32 {
	if x != nil {
		return x.Priority2
	}
	return 0
}

func (x *ParamsReply) GetPpsOut() int32 {
	if x != nil {
		return x.PpsOut
	}
	return 0
}

func (x *ParamsReply) GetMhz10Out() int32 {
	if x != nil {
		return x.Mhz10Out
	}
	return 0
}

func (x *ParamsReply) GetSyncePort() int32 {
	if x != nil {
		return x.SyncePort
	}
	return 0
}

func (x *ParamsReply) GetSyncOpt() int32 {
	if x != nil {
		return x.SyncOpt
	}
	return 0
}

var File_tsynctl_tsynctl_proto protoreflect.FileDescriptor

var file_tsynctl_tsynctl_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2f, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x1f, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x22, 0x1f, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x46, 0x0a, 0x0a, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72,
	0x65, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x72, 0x65, 0x76, 0x22, 0xfd,
	0x01, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x77,
	0x6f, 0x53, 0x74, 0x65, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x77, 0x6f,
	0x53, 0x74, 0x65, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x70, 0x73, 0x4f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x70, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x68,
	0x7a, 0x31, 0x30, 0x4f, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x68,
	0x7a, 0x31, 0x30, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x65,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x74, 0x32, 0xc1,
	0x02, 0x0a, 0x07, 0x54, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x12, 0x2f, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x2e, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x2e, 0x74, 0x73, 0x79, 0x6e, 0x63,
	0x74, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x74, 0x73, 0x79, 0x6e, 0x63,
	0x74, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x2e, 0x74, 0x73,
	0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x74, 0x73,
	0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x31, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0e, 0x2e,
	0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e,
	0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x6c,
	0x61, 0x72, 0x6d, 0x73, 0x12, 0x0e, 0x2e, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12, 0x33, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e, 0x2e, 0x74, 0x73, 0x79,
	0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x74, 0x73, 0x79,
	0x6e, 0x63, 0x74, 0x6c, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x5d, 0x0a, 0x1c, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x74,
	0x73, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x74, 0x73, 0x79, 0x6e, 0x63,
	0x74, 0x6c, 0x42, 0x0b, 0x54, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69,
	0x6c, 0x69, 0x63, 0x6f, 0x6d, 0x64, 0x6b, 0x2f, 0x73, 0x74, 0x73, 0x2d, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x73, 0x79, 0x6e, 0x63, 0x74,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tsynctl_tsynctl_proto_rawDescOnce sync.Once
	file_tsynctl_tsynctl_proto_rawDescData = file_tsynctl_tsynctl_proto_rawDesc
)

func file_tsynctl_tsynctl_proto_rawDescGZIP() []byte {
	file_tsynctl_tsynctl_proto_rawDescOnce.Do(func() {
		file_tsynctl_tsynctl_proto_rawDescData = protoimpl.X.CompressGZIP(file_tsynctl_tsynctl_proto_rawDescData)
	})
	return file_tsynctl_tsynctl_proto_rawDescData
}

var file_tsynctl_tsynctl_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tsynctl_tsynctl_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: tsynctl.Empty
	(*StatusReply)(nil), // 1: tsynctl.StatusReply
	(*ModeReply)(nil),   // 2: tsynctl.ModeReply
	(*TimeReply)(nil),   // 3: tsynctl.TimeReply
	(*ClassReply)(nil),  // 4: tsynctl.ClassReply
	(*AlarmReply)(nil),  // 5: tsynctl.AlarmReply
	(*ParamsReply)(nil), // 6: tsynctl.ParamsReply
}
var file_tsynctl_tsynctl_proto_depIdxs = []int32{
	0, // 0: tsynctl.Tsynctl.GetMode:input_type -> tsynctl.Empty
	0, // 1: tsynctl.Tsynctl.GetStatus:input_type -> tsynctl.Empty
	0, // 2: tsynctl.Tsynctl.GetTime:input_type -> tsynctl.Empty
	0, // 3: tsynctl.Tsynctl.GetClass:input_type -> tsynctl.Empty
	0, // 4: tsynctl.Tsynctl.StreamAlarms:input_type -> tsynctl.Empty
	0, // 5: tsynctl.Tsynctl.GetParams:input_type -> tsynctl.Empty
	2, // 6: tsynctl.Tsynctl.GetMode:output_type -> tsynctl.ModeReply
	1, // 7: tsynctl.Tsynctl.GetStatus:output_type -> tsynctl.StatusReply
	3, // 8: tsynctl.Tsynctl.GetTime:output_type -> tsynctl.TimeReply
	4, // 9: tsynctl.Tsynctl.GetClass:output_type -> tsynctl.ClassReply
	5, // 10: tsynctl.Tsynctl.StreamAlarms:output_type -> tsynctl.AlarmReply
	6, // 11: tsynctl.Tsynctl.GetParams:output_type -> tsynctl.ParamsReply
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tsynctl_tsynctl_proto_init() }
func file_tsynctl_tsynctl_proto_init() {
	if File_tsynctl_tsynctl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tsynctl_tsynctl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsynctl_tsynctl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsynctl_tsynctl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsynctl_tsynctl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsynctl_tsynctl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsynctl_tsynctl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tsynctl_tsynctl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tsynctl_tsynctl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tsynctl_tsynctl_proto_goTypes,
		DependencyIndexes: file_tsynctl_tsynctl_proto_depIdxs,
		MessageInfos:      file_tsynctl_tsynctl_proto_msgTypes,
	}.Build()
	File_tsynctl_tsynctl_proto = out.File
	file_tsynctl_tsynctl_proto_rawDesc = nil
	file_tsynctl_tsynctl_proto_goTypes = nil
	file_tsynctl_tsynctl_proto_depIdxs = nil
}
